const $=id=>document.getElementById(id); const canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
let sourceImage=null, roi=null, roiManual=false, currentResult=null;
const els={stage:$('stage'),guide:$('guide'),roi:$('roi'),status:$('status'),mode:$('modeSelect'),result:$('resultCard'),camera:$('cameraInput'),photo:$('photoInput')};
$('guideToggle').addEventListener('change',e=>els.guide.classList.toggle('hidden',!e.target.checked));
$('resetBtn').onclick=reset; $('autoDetectBtn').onclick=()=>{if(sourceImage){roi=detectGraph();roiManual=false;renderROI();setStatus('Auto ROI updated.')}};
$('manualBtn').onclick=()=>{if(!roi)return;roiManual=true;els.roi.classList.remove('hidden');setStatus('ROI adjustment enabled. Drag ROI to align with Energy per Band.');};
$('analyzeBtn').onclick=analyze;
[els.camera,els.photo].forEach(inp=>inp.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)loadFile(f)}));

function setStatus(s){els.status.textContent=s}
function reset(){sourceImage=null;roi=null;currentResult=null;ctx.clearRect(0,0,canvas.width,canvas.height);els.stage.classList.add('empty');els.roi.classList.add('hidden');els.result.classList.add('hidden');$('placeholder').classList.remove('hidden');['autoDetectBtn','manualBtn','analyzeBtn'].forEach(id=>$(id).disabled=true);els.camera.value='';els.photo.value='';setStatus('Ready')}
async function loadFile(file){setStatus('Loading image…');const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);sourceImage=img;const maxW=1600,scale=Math.min(1,maxW/img.naturalWidth);canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);ctx.drawImage(img,0,0,canvas.width,canvas.height);els.stage.classList.remove('empty');$('placeholder').classList.add('hidden');roi=detectGraph();renderROI();['autoDetectBtn','manualBtn','analyzeBtn'].forEach(id=>$(id).disabled=false);setStatus('Image loaded. Auto ROI detected.');analyze();};img.onerror=()=>setStatus('Could not read image.');img.src=url}

function luminanceAt(data,i){return (data[i]+data[i+1]+data[i+2])/3}
function detectGraph(){const w=canvas.width,h=canvas.height,img=ctx.getImageData(0,0,w,h).data;let best=null;const yStart=Math.floor(h*.05),yEnd=Math.floor(h*.62),xStart=Math.floor(w*.35);const step=Math.max(3,Math.floor(Math.min(w,h)/350));
  // coarse dark-density scan over graph-like windows; resilient to small iPhone crop changes
  const sizes=[[.28,.13],[.34,.16],[.40,.18],[.46,.21]].map(([rw,rh])=>[Math.floor(w*rw),Math.floor(h*rh)]);
  for(const [ww,hh] of sizes){for(let y=yStart;y<yEnd-hh;y+=Math.max(step*4,Math.floor(hh*.12))){for(let x=xStart;x<w-ww;x+=Math.max(step*4,Math.floor(ww*.10))){let dark=0,total=0;for(let yy=y;yy<y+hh;yy+=step){for(let xx=x;xx<x+ww;xx+=step){const i=(yy*w+xx)*4;if(luminanceAt(img,i)<50)dark++;total++}}const fill=dark/Math.max(1,total),aspect=ww/hh;if(fill>.18&&fill<.92&&aspect>1.5&&aspect<6.5){let score=fill*ww*hh*(1+x/w*.3);if(!best||score>best.score)best={x,y,w:ww,h:hh,score}}}}}
  if(best)return{x:best.x,y:best.y,w:best.w,h:best.h};
  return{x:Math.floor(w*.54),y:Math.floor(h*.13),w:Math.floor(w*.39),h:Math.floor(h*.23)}
}
function renderROI(){if(!roi)return;const r=canvas.getBoundingClientRect(),sx=r.width/canvas.width,sy=r.height/canvas.height;Object.assign(els.roi.style,{left:`${roi.x*sx}px`,top:`${roi.y*sy}px`,width:`${roi.w*sx}px`,height:`${roi.h*sy}px`});els.roi.classList.remove('hidden')}
window.addEventListener('resize',renderROI);

let drag=null;els.roi.addEventListener('pointerdown',e=>{if(!roiManual)return;e.preventDefault();els.roi.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,orig:{...roi}}});els.roi.addEventListener('pointermove',e=>{if(!drag||!roiManual)return;const r=canvas.getBoundingClientRect(),dx=(e.clientX-drag.x)*canvas.width/r.width,dy=(e.clientY-drag.y)*canvas.height/r.height;roi.x=EGSCore.clamp(drag.orig.x+dx,0,canvas.width-roi.w);roi.y=EGSCore.clamp(drag.orig.y+dy,0,canvas.height-roi.h);renderROI()});els.roi.addEventListener('pointerup',()=>drag=null);els.roi.addEventListener('pointercancel',()=>drag=null);

function checkedChannels(box){const img=ctx.getImageData(0,0,canvas.width,canvas.height).data,scale=box.w/300,startX=box.x-320*scale,cy=box.y+120*(box.h/135),step=36.3*scale,p=Math.max(9,Math.min(22,Math.round(14*scale))),out=[];for(let ch=0;ch<8;ch++){const cx=Math.round(startX+ch*step);let dark=0,total=0;for(let y=Math.max(0,Math.floor(cy));y<Math.min(canvas.height,Math.floor(cy+p));y++)for(let x=Math.max(0,Math.floor(cx));x<Math.min(canvas.width,Math.floor(cx+p));x++){const i=(y*canvas.width+x)*4;if(img[i]<85&&img[i+1]<85&&img[i+2]<85)dark++;total++}if(dark>=Math.max(5,total*.04))out.push(ch)}return out}
function inferMode(box,requested){if(requested!=='Auto')return{mode:requested,note:''};const img=ctx.getImageData(Math.max(0,box.x),Math.max(0,box.y),Math.min(box.w,canvas.width-box.x),Math.min(box.h,canvas.height-box.y)),w=Math.min(box.w,canvas.width-box.x),h=Math.min(box.h,canvas.height-box.y);let rows=[];for(let y=0;y<h;y++){let gcount=0;for(let x=0;x<w;x++){const i=(y*w+x)*4,r=img.data[i],g=img.data[i+1],b=img.data[i+2];if(g>45&&g>r*1.28&&g>b*1.16)gcount++}if(gcount>w*.18)rows.push(y)}let groups=0,last=-99;for(const y of rows){if(y-last>2)groups++;last=y}return groups>=4&&groups<=5?{mode:'Noise',note:'Auto mode inferred from graph scale'}:{mode:'Gain',note:'Auto mode uncertain; Gain fallback used'}}
function noiseTop(box){const crop=ctx.getImageData(Math.max(0,box.x),Math.max(0,box.y),Math.min(box.w,canvas.width-box.x),Math.min(box.h,canvas.height-box.y)),w=Math.min(box.w,canvas.width-box.x),h=Math.min(box.h,canvas.height-box.y);let rows=[];for(let y=0;y<h;y++){let n=0;for(let x=0;x<w;x++){const i=(y*w+x)*4,r=crop.data[i],g=crop.data[i+1],b=crop.data[i+2];if(g>38&&g>r*1.28&&g>b*1.16)n++}if(n>w*.18)rows.push(y)}let groups=[];for(const y of rows){if(!groups.length||y-groups.at(-1).at(-1)>2)groups.push([y]);else groups.at(-1).push(y)}const last=groups.at(-1)||[],avg=last.length?last.reduce((s,v)=>s+v,0)/last.length:0,zero=avg>h*.63;return groups.length>=4&&zero?(groups.length-1)*.01:.04}
function traceSeries(box,top,mode,channel){const g=EGSCore.geometry(box),x0=Math.max(0,Math.floor(g.x0)),y0=Math.max(0,Math.floor(g.y0)),x1=Math.min(canvas.width-1,Math.floor(g.x1)),y1=Math.min(canvas.height-1,Math.floor(g.y1)),w=x1-x0+1,h=y1-y0+1,img=ctx.getImageData(x0,y0,w,h).data,xs=[],vals=[];for(let x=0;x<w;x++){let yy=[];for(let y=0;y<h;y++){const i=(y*w+x)*4,r=img[i],gg=img[i+1],b=img[i+2],mx=Math.max(r,gg,b),mn=Math.min(r,gg,b),bright=r+gg+b>360&&mx>130,colored=mx>105&&(mx-mn)>45,green=gg>55&&gg>r*1.35&&gg>b*1.25;let ok=channel===0?bright:(channel!=null?colored:(bright||colored));if(channel!==0&&green)ok=false;if(ok)yy.push(y)}if(yy.length){yy.sort((a,b)=>a-b);const q=mode==='Noise'?(x<w*(270/500)?.90:.60):.50,pos=(yy.length-1)*q,lo=Math.floor(pos),hi=Math.ceil(pos),py=yy[lo]+(yy[hi]-yy[lo])*(pos-lo);xs.push(x);vals.push((1-py/Math.max(1,h-1))*top)}}if(vals.length<25)throw Error('Not enough signal pixels were found');return{xs,vals,width:w}}
function overlay(result){ctx.drawImage(sourceImage,0,0,canvas.width,canvas.height);const b=result.box,g=EGSCore.geometry(b),split=EGSCore.splitX(b);ctx.lineWidth=Math.max(2,canvas.width/500);ctx.strokeStyle='#ff3c4b';ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.strokeStyle='#ffd23f';ctx.beginPath();ctx.moveTo(split,g.y0);ctx.lineTo(split,g.y1);ctx.stroke();if(result.low!=null){ctx.strokeStyle='#00bff3';ctx.beginPath();ctx.moveTo(g.x0,EGSCore.valueY(b,result.low,result.top));ctx.lineTo(split,EGSCore.valueY(b,result.low,result.top));ctx.stroke()}if(result.high!=null){ctx.strokeStyle='#ff7f27';ctx.beginPath();ctx.moveTo(split,EGSCore.valueY(b,result.high,result.top));ctx.lineTo(g.x1,EGSCore.valueY(b,result.high,result.top));ctx.stroke()}}
function analyze(){if(!sourceImage||!roi)return;try{ctx.drawImage(sourceImage,0,0,canvas.width,canvas.height);const channels=checkedChannels(roi),mi=inferMode(roi,els.mode.value),analysisChannel=channels.length===1?channels[0]:null,top=mi.mode==='Noise'?noiseTop(roi):3.0,tr=traceSeries(roi,top,mi.mode,analysisChannel),lv=EGSCore.horizontalLevels(tr.xs,tr.vals,top,tr.width),digits=mi.mode==='Noise'?4:2,msg=[];if(mi.note)msg.push(mi.note);if(!channels.length)msg.push('Channel unknown; signal analysis continued');else if(channels.length>1)msg.push('Multiple channel candidates; combined signal analysis used');currentResult={mode:mi.mode,channels,low:+lv.low.toFixed(digits),high:+lv.high.toFixed(digits),confidence:lv.confidence,box:{...roi},top,message:msg.join('; ')};overlay(currentResult);showResult(currentResult);setStatus('Analysis complete.');}catch(e){setStatus(e.message||String(e));}}
function showResult(r){els.result.classList.remove('hidden');$('modeOut').textContent=r.mode;$('channelOut').textContent=r.channels.length?r.channels.join(','):'Unknown';$('confidenceOut').textContent=`${Math.round(r.confidence*100)}%`;$('lowOut').textContent=r.mode==='Noise'?r.low.toFixed(4):r.low.toFixed(2);$('highOut').textContent=r.mode==='Noise'?r.high.toFixed(4):r.high.toFixed(2);const ok=EGSCore.spec(r.mode,r.low,r.high),sp=$('specOut');sp.textContent=ok?'IN':'OUT';sp.className=ok?'spec-in':'spec-out';$('messageOut').textContent=r.message||'—'}

if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
